apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetes-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubernetes-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80