# Source: https://www.google.com/url?client=internal-element-cse&cx=013288817511911618469:elfqqbqldzg&q=https://discuss.kubernetes.io/t/is-it-possible-to-set-the-mac-address-of-a-pod-container/11602&sa=U&ved=2ahUKEwjj_KqM6eT8AhX2caQEHa7PAswQFnoECAAQAg&usg=AOvVaw1wMFTVJGKG-gp4IKC8Ubfv
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: netshoot
  template:
    metadata:
      labels:
        name: netshoot
    spec:
      # serviceAccountName: netshoot-sa
      containers:
        - name: netshoot
          image: nicolaka/netshoot
          command: [“sleep”]
          args: [“infinity”]
          imagePullPolicy: Always
#          securityContext:
#           capabilities:
#              add: [“NET_ADMIN”]