apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    frontend ambassador
      bind *:8080
      default_backend ambassador_test_svc
    backend ambassador_test_svc
      server svc ambassador-test-svc:8081
---
apiVersion: v1
kind: Pod
metadata:
  name: ambassador-test
spec:
  containers:
    - name: main
      image: radial/busyboxplus:curl
      command: ['sh', '-c', 'while true; do curl localhost:8080; sleep 5; done']
    - name: ambassador
      image: haproxy:2.4
      volumeMounts:
        - name: config
          mountPath: /usr/local/etc/haproxy/
  volumes:
    - name: config
      configMap:
        name: haproxy-config