apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-test
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: busybox:stable
      command: ['sh', '-c', 'cat /data/data.txt']
      volumeMounts:
        - name: host-data
          mountPath: /data
  volumes:
    - name: host-data
      hostPath:
        path: /etc/hostPath
        type: Directory