apiVersion: v1
kind: Pod
metadata:
  name: securitycontext-pod
spec:
  containers:
    - name: busybox
      image: busybox:stable
      command: ['sh', '-c', 'while true; do echo Running...; sleep 5; done']
      securityContext:
        runAsUser: 3000 # container process will run as user ID 3000
        runAsGroup: 4000 # container process will run as group ID 4000
        allowPrivilegeEscalation: false # Disables privileged mode for the container
        readOnlyRootFilesystem: true # Marks the container's root filesystem read-only